taskProject/taskProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks')),
]

taskProject/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('<int:pk>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

taskProject/tasks/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Task(models.Model):
    name = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    proj = models.CharField(max_length=200)
    status = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('tasks:single', args=[self.id])
    
    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name

class TimeEntry(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time   = models.DateTimeField()
    
    def __str__(self):
        return f"{self.id}: {self.start_time} {self.end_time}"

taskProject/tasks/forms.py
from django import forms
from .models import Task, TimeEntry

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

class TimeEntryForm(forms.ModelForm):
    class Meta:
        model = TimeEntry
        fields = "__all__"

taskProject/tasks/views.py
from django.shortcuts import render
from .models import Task
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
class IndexView(ListView):
    model = Task
    template_name = 'tasks/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
    model = Task
    pk_url_kwarg = 'pk'
    template_name = 'tasks/single.html'
    context_object_name = 'task'

class TasksView(ListView):
    model = Task
    template_name = 'tasks/tasks.html'
    context_object_name = 'task_list'

class AddView(CreateView):
    model = Task
    template_name = 'tasks/add.html'
    fields = '__all__'
    success_url = reverse_lazy('tasks:tasks')

class EditView(UpdateView):
    model = Task
    template_name = 'tasks/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('tasks:tasks')
    

class Delete(DeleteView):
    model = Task
    template_name = 'tasks/confirm-delete.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('tasks:tasks')

taskProject/templates/tasks/add.html
{% extends 'tasks/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container pt-5">
    <form method="POST">
        {% csrf_token %} 
        {% for field in form.visible_fields %} 
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class = "help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span> Submit
            </button>
            <a href="{% url 'tasks:tasks' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

taskProject/templates/tasks/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Task Tracker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
    <body>
    {% include 'tasks/navbar.html' %}
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

taskProject/templates/tasks/confirm-delete.html
{% extends 'tasks/base.html' %} 
{% block content %} 

<div class="container pt-5">
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"</p>
        <input type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

taskProject/templates/tasks/edit.html
{% extends 'tasks/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5">
    <form method="POST" novalidate>
        {% csrf_token %} 
        {% for field in form.visible_fields %} 
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class = "help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span> Edit
            </button>
            <a href="{% url 'tasks:tasks' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

taskProject/templates/tasks/index.html
{% extends 'tasks/base.html' %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
        {% for task in index %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h4 class=""><a href="{{ task.get_absolute_url }}">{{ task.name }}</a></h4>
                         <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="">
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

taskProject/templates/tasks/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand d-flex align-items-center" href="">Task Tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:tasks' %}">Manage Tasks</a>
        </li>
      </ul>
    </div>
</nav>

taskProject/templates/tasks/single.html
{% extends 'tasks/base.html' %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-12 pt-5">
                <h2 class="pt-5">{{task.name}}</h2>
                <h3 class="pt-5">{{task.proj}}</h3> 
                <p>{{task.desc}}</p>
                <h3>{{task.status}}</h3>
            </div>
        </div>
    </div>
</div>

{% endblock %}

taskProject/templates/tasks/tasks.html
{% extends 'tasks/base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-brand">Task Administration</div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'tasks:add' %}">Add New</a>
            </li>
        </ul>
    </div>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
        {% for task in task_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h4 class="lead"><a class="text-dark" href="{% url 'tasks:single' task.pk %}">{{ task.name }}</a></h4>
                         <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{{ task.get_absolute_url }}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">View</a>
                            <a href="{% url 'tasks:edit' task.pk %}" class="btn btn-sm btn-outline-secondart" role="button" aria-pressed="true">Edit</a>
                            <a href="{% url 'tasks:delete' task.pk %}" class="btn btn-sm btn-outline-secondart" role="button" aria-pressed="true">Delete</a>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}